  version: '3'

  services:
    develop:
      image: node:15.12.0
      volumes:
      - .:/workspace/
      command: /bin/sh -c "while sleep 1000; do :; done"     
  networks:
    default:
        external:
          name: quizweb_app_net